# Generated by Django 5.2.10 on 2026-03-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_created_at_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sellerprofile',
            table='seller_profile',
        ),
    ]
