# Generated by Django 5.2.10 on 2026-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Tshirt', 'Tshirt'), ('Shirt', 'Shirt'), ('Jeans', 'Jeans'), ('Watches', 'Watches'), ('Perfumes', 'Perfumes'), ('Hats', 'Hats'), ('Tops', 'Tops'), ('Dresses', 'Dresses'), ('Heels', 'Heels'), ('Bags', 'Bags'), ('Jewellery', 'Jewellery'), ('Kidswear', 'Kidswear'), ('Toys', 'Toys'), ('Shoes', 'Shoes')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
