# Generated by Django 5.2.10 on 2026-03-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_subcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
