# Generated by Django 5.2.10 on 2026-03-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productsize'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size')},
        ),
    ]
