# Generated by Django 5.2.10 on 2026-03-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_productsize_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='ord',
        ),
        migrations.AlterModelTable(
            name='sellerprofile',
            table='sellprofile',
        ),
    ]
