# Generated by Django 5.2.10 on 2026-03-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
